apiVersion: v1
kind: Service
metadata:
  name: hello-world-without-helm
  labels:
    app: hello-world
    type: no-helm
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hello-world
    type: no-helm
